#!/bin/bash
# Run ONCE on a Narval LOGIN node (has internet), AFTER setup_env.sh.
#
# Downloads everything a compute-node job needs to read purely from local
# disk: the Qwen2.5-VL backbone (via huggingface_hub snapshot_download) and
# the CATMuS Kraken pretrained model (via `kraken get`, then copied out to a
# fixed path so later jobs don't depend on kraken's own DOI/registry lookup,
# which would itself need network). Everything lands under
# $MODEL_CACHE ($PROJECT/road-barbados-htr/model_cache), never /scratch
# (purged) or /home (small quota).
#
# Override the backbone with: QWEN_MODEL_ID=Qwen/Qwen2.5-VL-3B-Instruct ./prefetch_models.sh
# (use a smaller backbone if your allocation's GPUs are memory-constrained).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_common.sh"

case "$(hostname -f 2>/dev/null || hostname)" in
    *login*|*narval[0-9]*) ;;
    *) echo "[WARN] hostname doesn't look like a Narval login node — this script needs internet access." >&2 ;;
esac

QWEN_MODEL_ID="${QWEN_MODEL_ID:-Qwen/Qwen2.5-VL-7B-Instruct}"
# Same default DOI already used as the Kraken starter's fallback pretrained
# model (starters/Kraken-OCR/config.yaml / train.py) — reused here rather
# than guessed, since it's what the Zindi starter kit itself points at.
CATMUS_MODEL_DOI="${CATMUS_MODEL_DOI:-10.5281/zenodo.10592716}"

mkdir -p "$MODEL_CACHE/hf" "$MODEL_CACHE/kraken" "$XDG_DATA_HOME"

load_narval_modules

echo ""
echo "=== Prefetching Qwen2.5-VL backbone: $QWEN_MODEL_ID ==="
if [ ! -d "$VENV_VLM" ]; then
    echo "[ERROR] $VENV_VLM not found — run setup_env.sh first." >&2
    exit 1
fi
# huggingface_hub download needs real network access, so unset the
# offline flag _common.sh exports for compute-node runs.
# shellcheck disable=SC1091
source "$VENV_VLM/bin/activate"
HF_HUB_OFFLINE=0 python - <<PYEOF
import os
from huggingface_hub import snapshot_download

model_id = os.environ["QWEN_MODEL_ID"]
cache_dir = os.environ["HF_HOME"]
print(f"[hf] snapshot_download({model_id!r}) -> {cache_dir}")
path = snapshot_download(repo_id=model_id, cache_dir=cache_dir)
print(f"[hf] done: {path}")
PYEOF
deactivate

echo ""
echo "=== Prefetching CATMuS Kraken pretrained model: $CATMUS_MODEL_DOI ==="
if [ ! -d "$VENV_KRAKEN" ]; then
    echo "[ERROR] $VENV_KRAKEN not found — run setup_env.sh first." >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$VENV_KRAKEN/bin/activate"
kraken get "$CATMUS_MODEL_DOI"
FOUND="$(find "$XDG_DATA_HOME" -iname '*.mlmodel' -newer "$SCRIPT_DIR/prefetch_models.sh" 2>/dev/null | head -1)"
if [ -z "$FOUND" ]; then
    # fall back to any .mlmodel under the kraken data dir if the -newer
    # filter missed it (e.g. clock skew)
    FOUND="$(find "$XDG_DATA_HOME" -iname '*.mlmodel' 2>/dev/null | head -1)"
fi
if [ -z "$FOUND" ]; then
    echo "[ERROR] 'kraken get' ran but no .mlmodel file was found under $XDG_DATA_HOME" >&2
    exit 1
fi
cp "$FOUND" "$MODEL_CACHE/kraken/catmus_pretrained.mlmodel"
echo "[kraken] cached at $MODEL_CACHE/kraken/catmus_pretrained.mlmodel"
deactivate

ENV_FILE="$SCRIPT_DIR/.env.narval"
cat > "$ENV_FILE" <<EOF
# Generated by prefetch_models.sh on $(date). Source this from job scripts
# (submit_*.sb already do) so compute nodes read models from local cache
# instead of trying to hit the network. Not committed to git — paths are
# specific to this allocation.
export PROJECT_REPO="$PROJECT_REPO"
export SCRATCH_REPO="$SCRATCH_REPO"
export MODEL_CACHE="$MODEL_CACHE"
export HF_HOME="$MODEL_CACHE/hf"
export TRANSFORMERS_CACHE="\$HF_HOME"
export HF_HUB_OFFLINE=1
export XDG_DATA_HOME="$MODEL_CACHE/xdg_data"
export QWEN_MODEL_ID="$QWEN_MODEL_ID"
export CATMUS_MODEL_PATH="$MODEL_CACHE/kraken/catmus_pretrained.mlmodel"
EOF
echo ""
echo "Wrote $ENV_FILE — submit_*.sb scripts source it automatically."
echo "Done. Compute-node jobs can now run fully offline against \$MODEL_CACHE."
